#!/usr/bin/env python3
"""
make_fonts.py — turn .ttf fonts into smooth (anti-aliased) fonts for the ESP32.

Why? The fonts built into graphics libraries are 1-bit: each pixel is either
on or off, so curves look jagged. This script renders each letter with 256
shades of "ink", producing the VLW format that LovyanGFX draws smoothly.

You only need to run this if you want to change the fonts or sizes:

    pip install pillow
    python3 tools/fonts/make_fonts.py

It writes firmware/AirTraffic/fonts_data.cpp and fonts_data.h.
"""
from pathlib import Path
import struct

from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent.parent / "firmware" / "AirTraffic"

ASCII = "".join(chr(c) for c in range(0x20, 0x7F)) + "°·→↑↓"  # + a few symbols
DIGITS = " 0123456789,.:-+/°FLAGNDftkmnhs%"

# (C name, font file, pixel size, Inter weight or None, characters)
FONTS = [
    ("font_label",   "Inter.ttf",               13, 560, ASCII),
    ("font_body",    "Inter.ttf",               16, 500, ASCII),
    ("font_body_b",  "Inter.ttf",               16, 650, ASCII),
    ("font_title",   "Inter.ttf",               22, 700, ASCII),
    ("font_hud",     "ChakraPetch-SemiBold.ttf", 18, None, ASCII),
    ("font_hud_l",   "ChakraPetch-Bold.ttf",    28, None, ASCII),
    ("font_display", "ChakraPetch-Bold.ttf",    44, None, ASCII),
    ("font_huge",    "ChakraPetch-Bold.ttf",    64, None, DIGITS + "ABCDEFGHIJKLMNOPQRSTUVWXYZ"),
]


def load_font(file: str, size: int, weight):
    font = ImageFont.truetype(str(HERE / file), size)
    if weight is not None:
        # Inter is a "variable font": one file, many weights. Axes are opsz, wght.
        axes = font.get_variation_axes()
        values = []
        for axis in axes:
            name = axis.get("name", b"")
            name = name.decode() if isinstance(name, bytes) else name
            if "eight" in name:
                values.append(weight)
            else:  # optical size: match the pixel size (clamped to the axis range)
                values.append(max(axis["minimum"], min(axis["maximum"], size)))
        font.set_variation_by_axes(values)
    return font


def render_glyph(font, ch):
    advance = round(font.getlength(ch))
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = x1 - x0, y1 - y0
    if ch == " " or w <= 0 or h <= 0:
        return (ord(ch), 0, 0, advance, 0, 0, b"")
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    return (ord(ch), h, w, advance, -y0, x0, img.tobytes())


def build_vlw(font, size, chars):
    glyphs = [render_glyph(font, ch) for ch in sorted(set(chars))]
    ascent, descent = font.getmetrics()
    out = bytearray(struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent))
    for code, h, w, adv, dy, dx, _ in glyphs:
        out += struct.pack(">7i", code, h, w, adv, dy, dx, 0)
    for *_, bitmap in glyphs:
        out += bitmap
    return bytes(out)


def c_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 24):
        lines.append("  " + ",".join(str(b) for b in data[i:i + 24]) + ",")
    lines.append("};\n")
    return "\n".join(lines)


def main():
    header = [
        "// AUTO-GENERATED by tools/fonts/make_fonts.py — do not edit by hand.",
        "// Fonts: Inter and Chakra Petch, SIL Open Font License (see tools/fonts/).",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    body = ['// AUTO-GENERATED by tools/fonts/make_fonts.py — do not edit by hand.',
            '#include "fonts_data.h"', ""]
    total = 0
    for name, file, size, weight, chars in FONTS:
        data = build_vlw(load_font(file, size, weight), size, chars)
        total += len(data)
        header.append(f"extern const uint8_t {name}[{len(data)}];  // {file} {size}px")
        body.append(c_array(name, data))
        print(f"{name:14s} {file:26s} {size:3d}px  {len(data)/1024:7.1f} KB")
    (OUT_DIR / "fonts_data.h").write_text("\n".join(header) + "\n")
    (OUT_DIR / "fonts_data.cpp").write_text("\n".join(body))
    print(f"total {total/1024:.1f} KB -> {OUT_DIR}")


if __name__ == "__main__":
    main()
