// AUTO-GENERATED by tools/fonts/make_fonts.py — do not edit by hand.
// Fonts: Inter and Chakra Petch, SIL Open Font License (see tools/fonts/).
#pragma once
#include <stdint.h>

extern const uint8_t font_label[10392];  // Inter.ttf 13px
extern const uint8_t font_body[13729];  // Inter.ttf 16px
extern const uint8_t font_body_b[14000];  // Inter.ttf 16px
extern const uint8_t font_title[23217];  // Inter.ttf 22px
extern const uint8_t font_hud[14449];  // ChakraPetch-SemiBold.ttf 18px
extern const uint8_t font_hud_l[31441];  // ChakraPetch-Bold.ttf 28px
extern const uint8_t font_display[72054];  // ChakraPetch-Bold.ttf 44px
extern const uint8_t font_huge[84921];  // ChakraPetch-Bold.ttf 64px
