// =============================================================================
//  theme.h  —  Colors and fonts. Change these to restyle the whole app!
// =============================================================================
//  The screen uses "RGB565" colors: 5 bits red, 6 bits green, 5 bits blue.
//  rgb(255, 128, 0) converts a normal 0-255 color into that format for you.
//
//  Try it: change kAccent to rgb(255, 80, 200) and re-upload for a pink radar.
// =============================================================================
#pragma once

#include <stdint.h>

#include "fonts_data.h"

constexpr uint16_t rgb(uint8_t r, uint8_t g, uint8_t b) {
  return static_cast<uint16_t>(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
}

namespace theme {

// --- Backgrounds (dark "night scope" glass) ---
constexpr uint16_t kBackground = rgb(5, 9, 15);
constexpr uint16_t kScope      = rgb(7, 14, 22);     // inside the radar circle
constexpr uint16_t kSurface    = rgb(13, 21, 32);    // cards and panels
constexpr uint16_t kSurfaceHi  = rgb(22, 34, 50);    // raised parts of panels
constexpr uint16_t kGrid       = rgb(26, 44, 60);    // range rings
constexpr uint16_t kGridBright = rgb(46, 74, 96);    // compass ticks

// --- Text ---
constexpr uint16_t kText       = rgb(232, 240, 248);
constexpr uint16_t kTextDim    = rgb(140, 160, 184);
constexpr uint16_t kTextMuted  = rgb(86, 104, 126);

// --- Meaningful colors ---
constexpr uint16_t kAccent     = rgb(61, 242, 196);  // radar sweep, selection
constexpr uint16_t kAccentDeep = rgb(10, 70, 64);
constexpr uint16_t kWarning    = rgb(255, 181, 71);
constexpr uint16_t kEmergency  = rgb(255, 77, 94);
constexpr uint16_t kHome       = rgb(255, 255, 255);

// Altitude colors, low to high (index = fmt::altitudeBand()).
constexpr uint16_t kAltitude[6] = {
    rgb(138, 148, 166),  // on the ground
    rgb(255, 122, 61),   // below 1,000 ft
    rgb(255, 197, 61),   // below 5,000 ft
    rgb(126, 224, 106),  // below 15,000 ft
    rgb(61, 214, 242),   // below 30,000 ft
    rgb(177, 140, 255),  // cruising
};

// --- Fonts (generated by tools/fonts/make_fonts.py) ---
//   Inter: clean and easy to read for labels.
//   Chakra Petch: squared-off "cockpit display" look for numbers and titles.
enum class Font : uint8_t { Label, Body, BodyBold, Title, Hud, HudLarge, Display, Huge, Count };

}  // namespace theme
